version: '2'
services:

  # The Application
  app:
    build:
      context: ""
      dockerfile: ./docker/webserver/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./laravel-playground/:/var/www
      - ./docker/webserver/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      XDEBUG_CONFIG: remote_host=172.19.0.1
      DB_PORT: 3306
      DB_HOST: database

  # The Web Server
  web:
    build:
      context: ""
      dockerfile: ./docker/webserver/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8081:80

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata:
